export const EVENTS = [
  {
    id: "Board meeting",
    title: "Board meeting",
    start: "Thu Dec 07 2023 09:00:00 GMT+0700 (Indochina Time)",
    end: "Thu Dec 07 2023 13:00:00 GMT+0700 (Indochina Time)",
    duration: "2 month(s)",
    rooms: ["rooms1"],
    lastUpdated: "",
    createdBy: "Username",
    modifiedBy: "",
    type: "I",
    description: "Board meeting Event",
    confirmed: "1",
    allDay: false,
    repeatType: "1",
  },
  {
    id: "MS training",
    title: "MS training",
    start: "Sat Dec 09 2023 14:00:00 GMT+0700 (Indochina Time)",
    end: "Sat Dec 09 2023 16:30:00 GMT+0700 (Indochina Time)",
    duration: "2 month(s)",
    rooms: ["rooms1", "rooms2"],
    lastUpdated: "",
    createdBy: "Username",
    modifiedBy: "",
    type: "E",
    description: "MS trainin",
    confirmed: "0",
    allDay: true,
    repeatType: "2",
  },
  {
    id: "Team lead meeting",
    title: "Team lead meeting",
    start: "Sun Dec 10 2023 08:30:00 GMT+0700 (Indochina Time)",
    end: "Sun Dec 10 2023 12:30:00 GMT+0700 (Indochina Time)",
    duration: "2 month(s)",
    rooms: ["rooms1"],
    lastUpdated: "",
    createdBy: "Username",
    modifiedBy: "",
    type: "I",
    description: "Board meeting Event",
    confirmed: "1",
    allDay: false,
    repeatType: "3",
  },
  {
    id: "Birthday Party",
    title: "Birthday Party",
    start: "Sat Dec 16 2023 07:00:00 GMT+0700 (Indochina Time)",
    end: "Mon Dec 18 2023 10:30:00 GMT+0700 (Indochina Time)",
    duration: "2 month(s)",
    rooms: ["rooms1"],
    lastUpdated: "",
    createdBy: "Username",
    modifiedBy: "",
    type: "I",
    description: "Board meeting Event",
    confirmed: "1",
    allDay: false,
    repeatType: "4",
  },
];
