export const EVENTS = [
  {
    id: "0",
    title: "Board meeting",
    start: new Date(2023, 11, 7, 9, 0, 0),
    end: new Date(2023, 11, 7, 13, 0, 0),
    duration: "2 month(s)",
    rooms: ["rooms1"],
    lastUpdated: "",
    createdBy: "Username",
    modifiedBy: "",
    type: "I",
    description: "Board meeting Event",
    confirmed: "1",
    repeatType: "0",
    allDay: false,
    repInterval: "5",
    repEndDt: "2023-01-01",
    skip: false,
    repDay0: "",
    repDay1: "",
    repDay2: "",
    repDay3: "",
    repDay4: "",
    repDay5: "",
    repDay6: "",
    monthlySelect: "",
    monthAbsolute: "",
    monthRelativeOrd: "",
    monthRelativeDay: "",
  },
  {
    id: "1",
    title: "MS training",
    start: new Date(2023, 11, 9, 14, 0, 0),
    end: new Date(2023, 11, 9, 16, 30, 0),
    duration: "2 month(s)",
    rooms: ["rooms1", "rooms2"],
    lastUpdated: "",
    createdBy: "Username",
    modifiedBy: "",
    type: "E",
    description: "MS trainin",
    confirmed: "0",
    repeatType: "2",
    allDay: true,
    repInterval: "5",
    repEndDt: "2023-01-01",
    skip: false,
    repDay0: "",
    repDay1: "",
    repDay2: "",
    repDay3: "",
    repDay4: "",
    repDay5: "",
    repDay6: "",
    monthlySelect: "",
    monthAbsolute: "",
    monthRelativeOrd: "",
    monthRelativeDay: "",
  },
  {
    id: "2",
    title: "Team lead meeting",
    start: new Date(2023, 11, 10, 8, 30, 0),
    end: new Date(2023, 11, 10, 12, 30, 0),
    duration: "2 month(s)",
    rooms: ["rooms1"],
    lastUpdated: "",
    createdBy: "Username",
    modifiedBy: "",
    type: "I",
    description: "Board meeting Event",
    confirmed: "1",
    repeatType: "0",
    allDay: false,
    repInterval: "5",
    repEndDt: "2023-01-01",
    skip: false,
    repDay0: "",
    repDay1: "",
    repDay2: "",
    repDay3: "",
    repDay4: "",
    repDay5: "",
    repDay6: "",
    monthlySelect: "",
    monthAbsolute: "",
    monthRelativeOrd: "",
    monthRelativeDay: "",
  },
  {
    id: "11",
    title: "Birthday Party",
    start: new Date(2023, 11, 16, 7, 0, 0),
    end: new Date(2023, 11, 18, 10, 30, 0),
    duration: "2 month(s)",
    rooms: ["rooms1"],
    lastUpdated: "",
    createdBy: "Username",
    modifiedBy: "",
    type: "I",
    description: "Board meeting Event",
    confirmed: "1",
    repeatType: "0",
    allDay: true,
    repInterval: "5",
    repEndDt: "2023-01-01",
    skip: false,
    repDay0: "",
    repDay1: "",
    repDay2: "",
    repDay3: "",
    repDay4: "",
    repDay5: "",
    repDay6: "",
    monthlySelect: "",
    monthAbsolute: "",
    monthRelativeOrd: "",
    monthRelativeDay: "",
  },
];
